export const EVENTS = Object.freeze({
    SIGN_UP: "SIGN_UP",
    HEART_BEAT: "HEART_BEAT",
    LOBBY: "LOBBY",
    MATCH_MAKE: "MATCH_MAKE",
    COLLECT_BOOT: "COLLECT_BOOT",
    SELECT_DEALER: "SELECT_DEALER",
    TURN: "TURN",
    TAKE_TURN: "TAKE_TURN",
    LEAVE_TABLE: "LEAVE_TABLE",
    SCORE_BOARD: "SCORE_BOARD",
    REJOIN: "REJOIN"
})