const exportObject = {
    PREFIX: {
        LIST: 'list',
        DECK: 'deck',
        MOVE: 'move',
        QUEUE: 'queue',
        HASH: 'hash',
        PLAYER: 'player',
        DISCONNECTED: 'dis',
        GAME_TABLE: 'TABLE',
        ROUND: 'ROUND',
        PLAYER_GAME_PLAY: 'PGP',
        ROUND_SCOREBOARD: 'RSB',
        TABLE_GAME_PLAY: 'TGP',
        SCORE_HISTORY: 'score_history',
        SPLIT_REQUEST: 'split',
        BID: 'bid',
        REJOIN_HISTORY: 'rejoin_history',
        USER: 'user',
        TABLE_HISTORY: 'table_history',
        TURN_HISTORY: 'turn_history',
        PLAYER_HISTORY: 'player_history',
        SCORE_BOARD_HISTORY: 'score_board_history',
        ROUND_HISTORY: 'round_history',
        LOBBY_HISTORY: 'lobby_history',
        GAME_OVER_AFTER_REMAIN_USERS: `GO_remain_users_history`,
        ONLINEPLAYER: 'activePlayer',
        ONLINE_PLAYER_LOBBY: 'activePlayerInLobby',
        TRACKEDLOBBY: "trackedLobby",
        LOBBY_DETAIL: 'lobbyDetail',
        ONLINE_USER_COUNTER: 'online_player',
        PROJECT_HANDLER: 'projectHandler'
    },
};

export = exportObject;
