export const TABLE_STATE = Object.freeze({
    WATING_PLAYER: "WATING_PLAYER",
    ROUND_TIMER_START: "ROUND_TIMER_START",
    COLLECT_BOOT: "COLLECT_BOOT",
    SELECT_DEALER: "SELECT_DEALER",
    PLAYING_START: "PLAYING_START",
    SCORE_BOARD: "SCORE_BOARD",
})